/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AiActivityRouteImport } from './routes/ai-activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalLeadIdRouteImport } from './routes/portal.$leadId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiRateRouteImport } from './routes/api.rate'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminBuildersRouteImport } from './routes/admin/builders'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as ApiCronSyncLeadsRouteImport } from './routes/api.cron.sync-leads'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AiActivityRoute = AiActivityRouteImport.update({
  id: '/ai-activity',
  path: '/ai-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLeadIdRoute = PortalLeadIdRouteImport.update({
  id: '/portal/$leadId',
  path: '/portal/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRateRoute = ApiRateRouteImport.update({
  id: '/api/rate',
  path: '/api/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildersRoute = AdminBuildersRouteImport.update({
  id: '/admin/builders',
  path: '/admin/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncLeadsRoute = ApiCronSyncLeadsRouteImport.update({
  id: '/api/cron/sync-leads',
  path: '/api/cron/sync-leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-activity': typeof AiActivityRoute
  '/appointments': typeof AppointmentsRoute
  '/feedback': typeof FeedbackRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/rate': typeof ApiRateRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$leadId': typeof PortalLeadIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/sync-leads': typeof ApiCronSyncLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-activity': typeof AiActivityRoute
  '/appointments': typeof AppointmentsRoute
  '/feedback': typeof FeedbackRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/rate': typeof ApiRateRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$leadId': typeof PortalLeadIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/sync-leads': typeof ApiCronSyncLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-activity': typeof AiActivityRoute
  '/appointments': typeof AppointmentsRoute
  '/feedback': typeof FeedbackRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/builders': typeof AdminBuildersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/rate': typeof ApiRateRoute
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$leadId': typeof PortalLeadIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/sync-leads': typeof ApiCronSyncLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-activity'
    | '/appointments'
    | '/feedback'
    | '/leads'
    | '/login'
    | '/messages'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/team'
    | '/admin/billing'
    | '/admin/builders'
    | '/admin/settings'
    | '/admin/users'
    | '/api/rate'
    | '/invite/$token'
    | '/portal/$leadId'
    | '/admin/'
    | '/api/cron/sync-leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-activity'
    | '/appointments'
    | '/feedback'
    | '/leads'
    | '/login'
    | '/messages'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/team'
    | '/admin/billing'
    | '/admin/builders'
    | '/admin/settings'
    | '/admin/users'
    | '/api/rate'
    | '/invite/$token'
    | '/portal/$leadId'
    | '/admin'
    | '/api/cron/sync-leads'
  id:
    | '__root__'
    | '/'
    | '/ai-activity'
    | '/appointments'
    | '/feedback'
    | '/leads'
    | '/login'
    | '/messages'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/team'
    | '/admin/billing'
    | '/admin/builders'
    | '/admin/settings'
    | '/admin/users'
    | '/api/rate'
    | '/invite/$token'
    | '/portal/$leadId'
    | '/admin/'
    | '/api/cron/sync-leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiActivityRoute: typeof AiActivityRoute
  AppointmentsRoute: typeof AppointmentsRoute
  FeedbackRoute: typeof FeedbackRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ReportsRoute: typeof ReportsRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBuildersRoute: typeof AdminBuildersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiRateRoute: typeof ApiRateRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PortalLeadIdRoute: typeof PortalLeadIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiCronSyncLeadsRoute: typeof ApiCronSyncLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-activity': {
      id: '/ai-activity'
      path: '/ai-activity'
      fullPath: '/ai-activity'
      preLoaderRoute: typeof AiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$leadId': {
      id: '/portal/$leadId'
      path: '/portal/$leadId'
      fullPath: '/portal/$leadId'
      preLoaderRoute: typeof PortalLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rate': {
      id: '/api/rate'
      path: '/api/rate'
      fullPath: '/api/rate'
      preLoaderRoute: typeof ApiRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builders': {
      id: '/admin/builders'
      path: '/admin/builders'
      fullPath: '/admin/builders'
      preLoaderRoute: typeof AdminBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-leads': {
      id: '/api/cron/sync-leads'
      path: '/api/cron/sync-leads'
      fullPath: '/api/cron/sync-leads'
      preLoaderRoute: typeof ApiCronSyncLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiActivityRoute: AiActivityRoute,
  AppointmentsRoute: AppointmentsRoute,
  FeedbackRoute: FeedbackRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ReportsRoute: ReportsRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBuildersRoute: AdminBuildersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiRateRoute: ApiRateRoute,
  InviteTokenRoute: InviteTokenRoute,
  PortalLeadIdRoute: PortalLeadIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiCronSyncLeadsRoute: ApiCronSyncLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
